/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recursion;

import javax.swing.JOptionPane;

/**
 *
 * @author Charly
 */
public class Formulario extends javax.swing.JFrame {

    Recursion recursion = new Recursion();
    int[][] matriz;

    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0: Numeros Primos", "1: Suma de numeros", "2: Suma de numeros pares", "3: Suma de numeros impares", "4: Factorial", "5: Fibonacci", "6: Multiplicacion", "7: Potencia", "8: Invertir", "9: Contar digitos", "10: Contar digitos pares", "11: Sumar digitos factoriales", "12: Sumar factoriales", "13: Sumar digitos factoriales pares", "14: Sumar digitos factoriales impares", "15: Sumar factoriales pares", "16: Sumar factoriales impares", "17: Contar los divisores de un numero", "18: Generar primera serie", "19: Calcular el capital de una inversion", "20: Generar segunda serie", "21: Suma de digitos primos de un número", "22: Division", "23: Generar serie con array", "24: Generar matriz desde las columnas", "25: Generar matriz triangular inferior", "26: Generar matriz gusanito desde las columnas", "27: Generar matriz L invertida" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 366, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int n = 0;
        int[] array = new int[0];
        if (jComboBox1.getSelectedIndex() < 24) {
            try {
                n = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un numeros: "));
                array = new int[n];
            } catch (NumberFormatException error) {
                System.out.println("Error:" + error);
            }
        }
        switch (jComboBox1.getSelectedIndex()) {
            case 0 -> {
                recursion.generarPrimos(array.length, 1, array, 0);
                for (int i = 0; i < array.length; i++) {
                    jTextArea1.append(array[i] + ", ");
                }
            }
            case 1 -> {
                jTextArea1.setText(recursion.sumaDeNumeros(n) + "");
            }
            case 2 -> {
                jTextArea1.setText(recursion.sumaDeNumerosPares(n) + "");
            }
            case 3 -> {
                jTextArea1.setText(recursion.sumaDeNumerosImpares(n) + "");
            }
            case 4 -> {
                jTextArea1.setText(recursion.factorial(n) + "");
            }
            case 5 -> {
                jTextArea1.setText(recursion.fibonacci(n) + "");
            }
            case 6 -> {
                int b = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un numeros: "));
                jTextArea1.setText(recursion.multiplicar(n, b) + "");
            }
            case 7 -> {
                int b = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un numeros: "));
                jTextArea1.setText(recursion.potencia(n, b) + "");
            }
            case 8 -> {
                jTextArea1.setText(recursion.invertir(n) + "");
            }
            case 9 -> {
                jTextArea1.setText(recursion.contarDigitos(n) + "");
            }
            case 10 -> {
                jTextArea1.setText(recursion.contarDigitosPares(n) + "");
            }
            case 11 -> {
                jTextArea1.setText(recursion.sumarDigitosFactoriales(n) + "");
            }
            case 12 -> {
                jTextArea1.setText(recursion.sumarFactoriales(n) + "");
            }
            case 13 -> {
                jTextArea1.setText(recursion.sumarDigitosFactorialesPares(n) + "");
            }
            case 14 -> {
                jTextArea1.setText(recursion.sumarDigitosFactorialesImpares(n) + "");
            }
            case 15 -> {
                jTextArea1.setText(recursion.sumarFactorialesPares(n) + "\n");
            }
            case 16 -> {
                jTextArea1.setText(recursion.sumarFactorialesImpares(n) + "\n");
            }
            case 17 -> {
                jTextArea1.append(recursion.divisores(n, 1, jTextArea1) + "\n");
            }
            case 18 -> {
                jTextArea1.setText("");
                jTextArea1.append(recursion.primeraSerie((float) n, 1, jTextArea1) + "");
            }
            case 19 -> {
                float monto = Float.parseFloat(JOptionPane.showInputDialog("Ingrese el monto de la inversión: "));
                float interes = Float.parseFloat(JOptionPane.showInputDialog("Ingrese el porcentaje del interes: "));
                jTextArea1.setText(recursion.inversion(monto, n, interes) + "\n");
            }
            case 20 -> {
                int x = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor de x: "));
                jTextArea1.append(recursion.segundaSerie(n, x, 2, jTextArea1) + "\n");
            }
            case 21 -> {
                jTextArea1.setText(recursion.sumaDeDigitosPrimos(n) + "\n");
            }
            case 22 -> {
                int b = Integer.parseInt(JOptionPane.showInputDialog("Ingrese un numeros: "));
                jTextArea1.setText(recursion.division(n, b) + "\n");
            }
            case 23 -> {
                recursion.generarSerieConArray(array, 0, 1, 1, 1);
                recursion.mostrarArray(array, 0, jTextArea1);
            }
            case 24 -> {
                pedirDatos();
                jTextArea1.setText("");
                recursion.generarMatrizFilasIntercaladas(matriz, 0, 0, 1);
                recursion.mostrarMatriz(matriz, 0, 0, jTextArea1);
            }
            case 25 -> {
                pedirDatos();
                jTextArea1.setText("");
                recursion.matrizTriangularInferior(matriz, 0, 0, 1);
                recursion.mostrarMatriz(matriz, 0, 0, jTextArea1);
            }
            case 26 -> {
                pedirDatos();
                jTextArea1.setText("");
                recursion.generarMatrizGusanitoVertical(matriz, 0, 0, 1);
                recursion.mostrarMatriz(matriz, 0, 0, jTextArea1);
            }
            case 27 -> {
                pedirDatos();
                jTextArea1.setText("");
                recursion.matrizL(matriz, 0, 0, 1);
                recursion.mostrarMatriz(matriz, 0, 0, jTextArea1);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void pedirDatos() {
        int filas = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de filas: "));
        int columnas = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de columnas: "));
        matriz = new int[filas][columnas];
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
